version: "3.9"
name: "GLKJDevHome"
services:
  mysql8:
    image: mysql:${MYSQL_VERSION}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 33060:3306  
    volumes:
      - my8Data:/var/lib/mysql  
      - ./conf/my8.cnf:/etc/my.cnf
    networks:
      - devNet  
  mysql5:
     image: mysql:${MYSQL_VERSION_OLD}
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 123456 
     ports:
      - 33061:3306 
     volumes:
      - my5Data:/var/lib/mysql 
      - ./conf/my5.cnf:/etc/my.cnf    
     networks:
      - devNet  
  mongo:
    image: mongo:${MONGO_VERSION}
    restart: always
    volumes:
      - mongoData:/data/db
      - ./conf/mongod.conf:/etc/mongod.conf
    ports:
      - 27018:27017
    # command: ["mongod","/etc/mongod.conf"]  
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456   
    networks:
      - devNet   
  mongo-express:
    image: mongo-express:${MONGO_EXPRESS_VERSION}
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017/  
    networks:
      - devNet   
  redis:
    image: redis:${REDIS_VERSION}   
    restart: always 
    ports:
      - 6379:6379
    networks:
      - devNet  
  rabbitmq:
    image: rabbitmq:management    
    restart: always 
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      -  rabbitmqData:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root  
      RABBITMQ_DEFAULT_PASS: 123456
networks:
  devNet:
    driver: bridge  
volumes:
  my8Data:
  my5Data:
  mongoData:
  rabbitmqData:

